// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package docker

import (
	"cloudphone/api/docker"
)

type ControllerV1 struct{}

func NewV1() docker.IDockerV1 {
	return &ControllerV1{}
}
