// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package adb

import (
	"cloudphone/api/adb"
)

type ControllerV1 struct{}

func NewV1() adb.IAdbV1 {
	return &ControllerV1{}
}
